import { shadcn } from '@clerk/themes';

const basePath = import.meta.env.BASE_URL.replace(/\/$/, '');

export const clerkAppearance = {
  theme: shadcn,
  cssLayerName: 'clerk',
  options: {
    logoPlacement: 'none' as const,
  },
  variables: {
    colorPrimary: 'hsl(213 100% 50%)',
    colorForeground: '#ffffff',
    colorMutedForeground: 'rgba(255,255,255,0.75)',
    colorDanger: 'hsl(0 100% 50%)',
    colorBackground: 'hsl(213 100% 50%)',
    colorInput: '#ffffff',
    colorInputForeground: '#000000',
    colorNeutral: '#000000',
    fontFamily: "'Boogaloo', cursive",
    borderRadius: '0px',
  },
  elements: {
    rootBox: 'w-full flex justify-center',
    cardBox: 'bg-primary halftone-blue comic-border comic-shadow w-[440px] max-w-full overflow-hidden',
    card: '!shadow-none !border-0 !bg-transparent !rounded-none',
    footer: '!shadow-none !border-0 !bg-transparent !rounded-none',
    headerTitle: 'font-display text-6xl uppercase tracking-widest text-white [text-shadow:_-3px_-3px_0_#000,_3px_-3px_0_#000,_-3px_3px_0_#000,_3px_3px_0_#000,_-3px_0px_0_#000,_3px_0px_0_#000,_0px_-3px_0_#000,_0px_3px_0_#000,_5px_5px_0_#000]',
    headerSubtitle: 'text-white/80 font-bold text-lg',
    socialButtonsBlockButtonText: 'text-black font-bold',
    socialButtonsBlockButton: 'border-2 border-black bg-white hover:bg-gray-100',
    formFieldLabel: 'text-white font-bold uppercase text-xs tracking-wide',
    formFieldInput: 'border-2 border-black focus:border-secondary bg-white text-black',
    formButtonPrimary: 'bg-secondary text-black border-2 border-black font-display text-lg uppercase shadow-[3px_3px_0_#000] hover:shadow-[5px_5px_0_#000] hover:-translate-y-0.5 transition-all',
    footerActionLink: 'text-secondary font-bold underline',
    footerActionText: 'text-white/80',
    footerAction: 'text-center',
    dividerText: 'text-white/70 font-medium',
    dividerLine: 'bg-white/30',
    identityPreviewEditButton: 'text-secondary',
    formFieldSuccessText: 'text-green-300',
    alertText: 'text-white',
    alert: 'border-2 border-destructive bg-destructive/20',
    otpCodeFieldInput: 'border-2 border-black bg-white text-black',
    formFieldRow: '',
    main: '',
    logoBox: 'mb-2',
    logoImage: 'h-16 w-16',
    badge: '!hidden',
  },
};
